### PR TITLE
Add jsx() support.

### PR DESCRIPTION
**Pull request by jeremyfa**
This PR adds support/syntax highlighting for the `jsx('...')` construct in the Haxe grammar that you can see in use with [react](https://github.com/massiveinteractive/haxe-react) haxelib.

Initial implementation was made on an alternative haxe syntax file for Atom editor (see https://github.com/massiveinteractive/haxe-react/issues/23), but it meant users had to use an alternative syntax file instead of just get haxe plugin.

This PR is thus a pragmatic attempt to improve coding experience when working with React + Haxe and vscode without having to use an alternative haxe syntax file (and prevent fragmentation).

I am aware it is a framework/library specific syntax, but still ended up thinking this is a reasonable approach to merge it with haxe default syntax file because it doesn't break any existing grammar file and all the _jsx_ part is isolated, keeping the _haxe_ part almost unchanged (see diff in commit). In addition it makes it much easier for haxe users to get started with Haxe + React with good JSX syntax highlighting.

To summarize:
* **CON** Framework specific syntax hardcoded in the grammar file
* **CON** Only works for this `jsx()` construct (single or double quotes), even though it could be improved to allow other generic keywords (tpl, xml, ...) which would make more readable inlined xml/html templates in haxe strings.
* **PRO** Better experience for Haxe users using haxe-react with vscode, by default
* **PRO** No need to use an alternative haxe syntax file
* **PRO** Doesn't break any existing Haxe syntax (JSX syntax is isolated and doesn't pollute the rest of the grammar file)
* **PRO** In case Haxe language gets inline XML support and Haxe-react switches to that, it would be easy to update the grammar file to the new syntax

Screenshot of the result in vscode:

capture d ecran 2017-06-22 a 13 00 49

I personally strongly advise to merge this because it would ensure any user who want to have this feature (which really improve readability when using react) wouldn't have to switch to an alternative haxe syntax file to do so, and would not break any existing syntax anyway.

### CODE REVIEW

**Comment by Simn** [comment]
> CON Framework specific syntax hardcoded in the grammar file

That's a really big CON for me... :(

**Comment by jeremyfa** [comment]
Right, but it is isolated as much as possible, and does improve user experience a lot when using React.

I am totally interested into finding a better solution, but having to use an alternative syntax file seems even worse, because it would mean having to port every new update to the haxe grammar to the alternative syntax continuously.

**Comment by elsassph** [comment]
That's looking great! 
Maybe if it's compatible with https://github.com/haxetink/tink_hxx as well that may be generic enough?

**Comment by nadako** [comment]
I wonder if we could somehow make this pluggable in a sense we have a single base file for normal haxe syntax, and a set of extension files that add rules, and then when building we generate a tmLanguage file for each extension, which can then somehow be selected as the main syntax file for haxe files...

**Comment by jeremyfa** [comment]
That could be an interesting option. As you can see in the diff of the PR, it's mostly about adding new entries at the end of the file, and inserting an include in the `method-call` part. If we are able to parse and dump YAML files, that's easy to patch.

**Comment by Gama11** [comment]
This should at the very least be moved into a separate `YAML-tmLanguage` file. It could then be included via `include: 'source.jsx'` or something like that (see the [hxml grammar](https://github.com/vshaxe/haxe-TmLanguage/blob/master/hxml.YAML-tmLanguage#L18)).

**Comment by Gama11** [comment]
Speaking of including grammars.. is there anything Haxe-specific about this jsx grammar? Because if not, there are probably existing ones that could be reused.

**Comment by Gama11** [comment]
I just checked out this branch and copied an example from haxe-react's readme - doesn't seem to work properly (notice how towards the end, `}` are highlighted as strings etc):



Also, highlighting `jsx` as a keyword feels wrong, for Haxe it's still just a regular function.

**Comment by back2dos** [comment]
So here's a crazy idea: 

What if the highlighting were applied to any string where the first non-white-space character is a `<` followed by an identifier? That would make non-"framework specific", right? Instead, strings containing markup would be highlighted nicely, including gems like [`Xml.parse('<${xml.nodeName}><a href="#$bookmarkID"></a></${xml.nodeName}>').firstElement();`](https://github.com/HaxeFoundation/haxe/issues/6359#issue-235449228).

**Comment by jeremyfa** [comment]
@Gama11 indeed it seems this case is not handled yet. That can be fixed however. Will take a look at it. Regarding `jsx` as a keyword, it is just a regular function for Haxe, yes, but following that logic we should not highlight anything in the string either as, for Haxe, it is just a string. `jsx` as a keyword makes it distinct from a regular function, because in some ways, it is (and is transformed at compile time to something else). But anyway if `jsx` as a keyword still feels wrong, it's ok to remove the `keyword` tag as long as it is still marked as something special in the grammar (`jsx` tag?) that allows themes to color it differently if needed.

@back2dos That's an idea I tried to implement back when I was using Atom, but syntax highlighting would break if I had a string with incomplete tag (like a string that opens a tag but doesn't close it etc...). It would be possible to make a grammar that doesn't break the whole file in that case, but that would be quite more complicated to implement I believe. Still, I like the idea (and this idea is implemented in IDEs like IntelliJ iirc).

**Comment by jeremyfa** [comment]
@Gama11 Seems that something behaves a bit differently compared to what I had on Atom, looking at the issue.

**Comment by jeremyfa** [comment]
@Gama11 Fixed. A `}` was flipped to `{` in the grammar file when porting it from atom to vscode. Should work now!

**Comment by jeremyfa** [comment]
> Speaking of including grammars.. is there anything Haxe-specific about this jsx grammar? Because if not, there are probably existing ones that could be reused.

The grammar initially done in Atom then ported to this PR was taken from "official" jsx grammar used in Atom. But the jsx grammar could not be used as is at it was still coupled with javascript and how we insert the inline xml in it... The same goes with this jsx-for-haxe: in the grammar is defined that we handle this syntax when the string is preceded with `jsx(`.

I think it's definitely a good idea to separate into multiple grammar files, but it seems fine to have our own "jsx-for-haxe" grammar. There are some cases that are different than original jsx, like adding a `$` before `{`, because it is valid in haxe.

**Comment by back2dos** [comment]
> [...] It would be possible to make a grammar that doesn't break the whole file in that case, but that would be quite more complicated to implement I believe

@jeremyfa Hmm, I must say I find it hard to read the syntax definition, so I can't really be the judge of that. That said, XML/HTML is context free, while a grammar that accepts a stream of opening tags, closing tags, self-closing tags and text-runs inbetween is regular (well, it stops being that when you deal with JSX shenanigans). That's why you might see XML parser built on SAX parsers, but not the other way around. Meaning there is *some* hope that this might be easy to do. It's really "just" `(text | openTag | closeTag | selfCloseTag)*` (maybe add in comments if you're into it).

The thing is that you thus get syntax highlighting also for things like

```haxe
return 
  "<foo>"
   + "<bar>Hoho</bar>"
  "</foo>";
```

And also it can handle HTML5, where the technically correct notation for void elements is e.g. `` (*without* self-closing or closing).

I'm not sure how much extra trouble that is, but it would cover a lot more cases ;)

**Comment by jeremyfa** [comment]
@back2dos Actually, what you are describing is already 90% done in the grammar file. The only difference is that it is currently encapsuled into the `jsx()` call instead of being matched over "any string that starts with `{` or `<` in order to prevent unexpected/wrong syntax coloring that would happen in cases like:

```
return "<foo";
```

```
return "<foo" + "bar>";
```

```
return "<foo='b";
```

```
return "{not clo";
```

```
return "<foo>Haha</foo";
```

But it is probably possible to improve the grammar to make these not mess up the file (ie. either detect the end of the string even in the middle of a tag, substring, ... or just not match the xml at all and just match a regular string because xml is considered invalid).

**Comment by jeremyfa** [comment]
@Simn @Gama11 @nadako In case we edit this pull request to remove the _framework specific_ part (remove any mention of jsx), and implement it like @back2dos proposed: match strings that have valid xml and in which the first non-whitespace character in the string is `<` (while still ensuring it doesn't break the file in case of invalid xml in the string), would you consider merging it?

**Comment by back2dos** [comment]
@jeremyfa Well, ok, if we stick to "the first non-white-space character is a `<` followed by an identifier" and add "the last non-white-space character is a `>`" that makes things more sensible. I wouldn't do it for `{` to be honest, because that can really mean *anything*, e.g. `haxe.Json.parse('{ "foo": "bar" }')`. There's really no point in highlighting that as markup.

This leaves us with the cases when someone writes (for whatever reason) `'<foo ^]/ blargh  &[*!?>'`, which will wrongly have markup highlighting applied. Let me speculate and claim that this is an edge case that we could all live with - so long as it doesn't mess up the highlighting of the rest of the file of course.

**Comment by Simn** [comment]
I'm against integrating it like this. It's not part of the Haxe language and should not be part of the Haxe syntax file. And no, I can't suggest an alternative at the moment.

**Comment by jeremyfa** [comment]
Agreeing on not matching `{` as a starting point for the same reasons you mentioned. Will try to change the grammar on another branch toward this solution (and probably make another PR if the result is satisfying). There might not be so much more work left to do so.

**Comment by elsassph** [comment]
Arbitrarily coloring all strings doesn't seem like a good idea.

**Comment by jeremyfa** [comment]
I wouldn't say it's "arbitrarily" coloring all string. There must be a condition (being "having some xml markup in it"). XML is pretty common (so common that there is an Xml parser in Haxe standard library), so I don't think it's completely absurd to want to integrate it properly in the editor (that's what IDEA/Webstorm do, iirc). Anyway, if it can't be merged, I am not going insist on it and will instead look for another solution (an additional plugin generated by patching haxe "official" syntax?).

Say hello to alternative syntaxes.

Closing this for now.

**Pull request closed without merging**
